# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-27 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planodecontas',
            name='new_classification',
        ),
    ]
