# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-30 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0003_auto_20180330_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planodecontas',
            name='account_type',
            field=models.CharField(max_length=7, verbose_name='Tipo Conta'),
        ),
    ]
