# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-30 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0004_auto_20180330_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planodecontas',
            name='account_type',
            field=models.CharField(max_length=8, verbose_name='Tipo Conta'),
        ),
    ]
