# Generated by Django 2.0.4 on 2018-04-04 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0005_auto_20180330_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custobovespa',
            name='lancamento',
        ),
        migrations.RemoveField(
            model_name='custocblc',
            name='lancamento',
        ),
        migrations.RemoveField(
            model_name='custocorretagem',
            name='lancamento',
        ),
        migrations.DeleteModel(
            name='CustoBovespa',
        ),
        migrations.DeleteModel(
            name='CustoCblc',
        ),
        migrations.DeleteModel(
            name='CustoCorretagem',
        ),
        migrations.DeleteModel(
            name='Lancamento',
        ),
    ]
