# Generated by Django 2.0.4 on 2018-04-09 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='participants',
        ),
    ]
