# Generated by Django 2.0.4 on 2018-04-11 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20180411_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='item_participantes', to=settings.AUTH_USER_MODEL),
        ),
    ]
