# Generated by Django 2.0.4 on 2018-04-25 21:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0007_auto_20180425_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='participants',
        ),
        migrations.AddField(
            model_name='booking',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
